Use balign 8 for 8 series, otherwise use align 8.
sifive/freedom-metal pull request #406
Opened 2021-06-25 15:43 UTC by lexus0

The performance numbers drop for e76, and s76 with coremark, and dhrystone due to [freedom-metal PR-374](https://github.com/sifive/freedom-metal/pull/374).
* For coremark: e76: 5.71 -> 5.69 ;s76: 5.72 -> 5.67
* For dhrystone: e76: 3.0 -> 2.97

I understand it is necessary for u84 (5.6 -> 5.77 in dhrystone).
Therefore, I develop a mechanism to use align or balign by recognizing RISCV_SERIES.
This mechanism need another PR in freedom-e-sdk.

2021-06-25 16:10 UTC, e-puerto requested changes
I have some difficulties understanding why align argv into crt0.S to balign 8 or align 8 (equivalent to balign 256) have some impact on coremark and dhrystone where both do not use argv.

2021-06-25 16:24 UTC, nick-knight commented
My best guess is it forces a stricter alignment on an ELF section that ends up containing this (after linking).

2021-06-25 16:30 UTC, lexus0 commented
I have no idea either. I just did some binary search to check which commit make performance drop for e76, and s76.
[This PR](https://github.com/sifive/freedom-metal/pull/374) was not merged when I was targeting the 7 series numbers..

2021-06-26 01:43 UTC, fuhle044 commented
We need to look at the map file for data layout. I suspect that the argv alignment is setting the default data sectiom alignment, which then affects the section combining alignments. Or the issue is actually in the linker script and it's doing a poor job with .sdsta/.data/.bss alignments.

2021-07-01 16:51 UTC, paul-walmsley-sifive commented
Hi folks, just to follow up here: we're concerned that this patch doesn't address the root cause of the problem, and that the root cause is poorly understood.  So at this time, we're not planning on merging this.  @fuhle044 can you assign somebody in your group to root-cause this issue?  Thanks

2021-07-01 17:32 UTC, nick-knight commented
FYI @fuchingy .

2021-07-01 18:38 UTC, fuhle044 commented
Already under investigation.

On Thu, Jul 1, 2021, 09:51 Paul Walmsley ***@***.***> wrote:

> Hi folks, just to follow up here: we're concerned that this patch doesn't
> address the root cause of the problem, and that the root cause is poorly
> understood. So at this time, we're not planning on merging this. @fuhle044
> <https://github.com/fuhle044> can you assign somebody in your group to
> root-cause this issue? Thanks
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sifive/freedom-metal/pull/406#issuecomment-872401392>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOB2QNSFTD3LI46XQV5DD7LTVSMIFANCNFSM47KDVSGQ>
> .
>

2021-07-02 10:12 UTC, lexus0 commented
hi all,

### In short

I think I will create another PR for new flags to fit `.balign 8` instead of having strange checking system to choose align or balign.

----

### details
The flag mining is something like tweak the performance based on what you have.
We start to tweak the performance  based on `.align 8`.
I think the performance drops from `.align 8` to `.balign 8` because the data layout didn't fit perfectly.


The flags that merged into master is based on `.align 8`.
I asked @DavidSTWChen that `.balign 8` is necessary for benchmark they are using,
and make more sense than `.align 8`.

I started another round to mind the flags to fit `.balign 8`.
They can meet the target but the flags are too long.
So I'm doing some reduction work right now.
I will create another PR for new flags once I finish my work.
Then we can close this PR, and related PR in fesdk-private.

2021-07-02 14:24 UTC, issuehsu commented
Drop this PR; we will resolve the performance drop issue with freedom-e-sdk-private PR#117

2021-07-02 14:24 UTC, closed without merging